//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All_Text {
            get {
                return ResourceManager.GetString("All_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories_Text {
            get {
                return ResourceManager.GetString("Categories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category_Text {
            get {
                return ResourceManager.GetString("Category_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments_Text {
            get {
                return ResourceManager.GetString("Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string Contact_Us_Text {
            get {
                return ResourceManager.GetString("Contact_Us_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Review.
        /// </summary>
        internal static string Disabled_Review_Text {
            get {
                return ResourceManager.GetString("Disabled_Review_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string Discover_Text {
            get {
                return ResourceManager.GetString("Discover_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured category.
        /// </summary>
        internal static string Featured_category_Text {
            get {
                return ResourceManager.GetString("Featured category_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by price.
        /// </summary>
        internal static string Filter_by_price_Text {
            get {
                return ResourceManager.GetString("Filter_by_price_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Category.
        /// </summary>
        internal static string Filter_Category_Text {
            get {
                return ResourceManager.GetString("Filter_Category_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Price.
        /// </summary>
        internal static string Filter_Price_Text {
            get {
                return ResourceManager.GetString("Filter_Price_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter_Text {
            get {
                return ResourceManager.GetString("Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        internal static string Has_Text {
            get {
                return ResourceManager.GetString("Has_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Text {
            get {
                return ResourceManager.GetString("Home_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        internal static string Hot_Text {
            get {
                return ResourceManager.GetString("Hot_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        internal static string Infomation_Text {
            get {
                return ResourceManager.GetString("Infomation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string items_Text {
            get {
                return ResourceManager.GetString("items_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        internal static string Load_more_Text {
            get {
                return ResourceManager.GetString("Load_more_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message_Text {
            get {
                return ResourceManager.GetString("Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsLetterEmailDuplicated.
        /// </summary>
        internal static string NewsLetterEmailDuplicated_Text {
            get {
                return ResourceManager.GetString("NewsLetterEmailDuplicated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsLetterSuccessful.
        /// </summary>
        internal static string NewsLetterSuccessful_Text {
            get {
                return ResourceManager.GetString("NewsLetterSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSuggestionNotice.
        /// </summary>
        internal static string NoSuggestionNotice_Text {
            get {
                return ResourceManager.GetString("NoSuggestionNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comments.
        /// </summary>
        internal static string No_Comments_Text {
            get {
                return ResourceManager.GetString("No_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image Available.
        /// </summary>
        internal static string No_Image_Available_Text {
            get {
                return ResourceManager.GetString("No_Image_Available_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Review.
        /// </summary>
        internal static string No_Review_Text {
            get {
                return ResourceManager.GetString("No_Review_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of stock.
        /// </summary>
        internal static string of_stock_Text {
            get {
                return ResourceManager.GetString("of stock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of_Text {
            get {
                return ResourceManager.GetString("of_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Comments.
        /// </summary>
        internal static string Other_Comments_Text {
            get {
                return ResourceManager.GetString("Other_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Product.
        /// </summary>
        internal static string Our_Product_Text {
            get {
                return ResourceManager.GetString("Our_Product_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string Out_Text {
            get {
                return ResourceManager.GetString("Out_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Posts.
        /// </summary>
        internal static string Popular_Posts_Text {
            get {
                return ResourceManager.GetString("Popular Posts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product is tagged to this.
        /// </summary>
        internal static string product_is_tagged_to_this_Text {
            get {
                return ResourceManager.GetString("product is tagged to this_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Related.
        /// </summary>
        internal static string Product_Related_Text {
            get {
                return ResourceManager.GetString("Product_Related_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Tags.
        /// </summary>
        internal static string Product_Tags_Text {
            get {
                return ResourceManager.GetString("Product_Tags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product_Text {
            get {
                return ResourceManager.GetString("Product_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string Read_more_Text {
            get {
                return ResourceManager.GetString("Read_more_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        internal static string results_Text {
            get {
                return ResourceManager.GetString("results_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews for this product.
        /// </summary>
        internal static string Reviews_for_this_product_Text {
            get {
                return ResourceManager.GetString("Reviews_for_this_product_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews_Text {
            get {
                return ResourceManager.GetString("Reviews_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale_Text {
            get {
                return ResourceManager.GetString("Sale_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to top.
        /// </summary>
        internal static string Scroll_to_top_Text {
            get {
                return ResourceManager.GetString("Scroll to top_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Article.
        /// </summary>
        internal static string Search_Article_Text {
            get {
                return ResourceManager.GetString("Search Article_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Tags.
        /// </summary>
        internal static string Search_by_Tags_Text {
            get {
                return ResourceManager.GetString("Search by Tags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Products.
        /// </summary>
        internal static string Search_Products_Text {
            get {
                return ResourceManager.GetString("Search_Products_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send_Text {
            get {
                return ResourceManager.GetString("Send_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string Shared_Text {
            get {
                return ResourceManager.GetString("Shared_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this post.
        /// </summary>
        internal static string Share_this_post_Text {
            get {
                return ResourceManager.GetString("Share this post_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        internal static string Showing_Text {
            get {
                return ResourceManager.GetString("Showing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name: A to Z.
        /// </summary>
        internal static string Sort_by_name__A_to_Z_Text {
            get {
                return ResourceManager.GetString("Sort by name: A to Z_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name: Z back A.
        /// </summary>
        internal static string Sort_by_name__Z_back_A_Text {
            get {
                return ResourceManager.GetString("Sort by name: Z back A_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by newness.
        /// </summary>
        internal static string Sort_by_newness_Text {
            get {
                return ResourceManager.GetString("Sort by newness_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by popularity.
        /// </summary>
        internal static string Sort_by_popularity_Text {
            get {
                return ResourceManager.GetString("Sort by popularity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by price: high to low.
        /// </summary>
        internal static string Sort_by_price__high_to_low_Text {
            get {
                return ResourceManager.GetString("Sort by price: high to low_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by price: low to high.
        /// </summary>
        internal static string Sort_by_price__low_to_high_Text {
            get {
                return ResourceManager.GetString("Sort by price: low to high_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit_Text {
            get {
                return ResourceManager.GetString("Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest By Blog Category.
        /// </summary>
        internal static string Suggest_By_Blog_Category_Text {
            get {
                return ResourceManager.GetString("Suggest_By_Blog_Category_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest By Category.
        /// </summary>
        internal static string Suggest_By_Category_Text {
            get {
                return ResourceManager.GetString("Suggest_By_Category_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest By Page.
        /// </summary>
        internal static string Suggest_By_Page_Text {
            get {
                return ResourceManager.GetString("Suggest_By_Page_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest By Post.
        /// </summary>
        internal static string Suggest_By_Post_Text {
            get {
                return ResourceManager.GetString("Suggest_By_Post_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest By Product.
        /// </summary>
        internal static string Suggest_By_Product_Text {
            get {
                return ResourceManager.GetString("Suggest_By_Product_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags_Text {
            get {
                return ResourceManager.GetString("Tags_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title_Text {
            get {
                return ResourceManager.GetString("Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful link.
        /// </summary>
        internal static string Useful_link_Text {
            get {
                return ResourceManager.GetString("Useful link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for.
        /// </summary>
        internal static string What_are_you_looking_for_Text {
            get {
                return ResourceManager.GetString("What are you looking for_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        internal static string Your_Comment_Text {
            get {
                return ResourceManager.GetString("Your_Comment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        internal static string Your_email_address_Text {
            get {
                return ResourceManager.GetString("Your email address_Text", resourceCulture);
            }
        }
    }
}
